import React from 'react'

export const About = () => {
    return (
        <div className='container my-4' >
            <h3>Read more about this app</h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi quos totam sequi ad, vero nesciunt accusamus, expedita ducimus amet consequuntur placeat, voluptate hic. Necessitatibus molestiae quia, assumenda cum voluptatum qui minus blanditiis doloribus, architecto delectus vitae dolor adipisci magni voluptatibus esse dolore possimus. Quod laborum magnam quo numquam officia recusandae tenetur iste deleniti quisquam ex placeat ipsam obcaecati fugit asperiores, modi, similique culpa ullam veniam animi maxime illum dignissimos? Eveniet quisquam quam at quia itaque vel laborum consectetur. Corporis id ipsum praesentium impedit at animi debitis inventore, laudantium vero quasi ducimus blanditiis fugit tenetur cupiditate illo rem ab velit error doloremque. Obcaecati, dicta? Doloremque id quaerat illum architecto obcaecati asperiores consequatur cum ducimus. Non labore quibusdam consequatur! Adipisci cumque quia voluptas. Error eum optio quam praesentium nesciunt porro reiciendis minima! Suscipit, iusto modi. Fuga asperiores laboriosam harum architecto eligendi. Architecto unde minima fuga dicta facere iure beatae molestias quis nam eligendi, enim soluta consectetur consequatur laborum velit repellendus culpa provident error. Nam quis a ullam, dolore officia tempore ad perferendis quas odio unde expedita est nostrum exercitationem, necessitatibus aspernatur dolores error? Veritatis ipsum eum saepe accusantium cum voluptate, corrupti obcaecati cumque, tenetur provident, ducimus quibusdam ut minima qui voluptatibus nostrum perspiciatis ipsa eveniet vitae architecto voluptas nisi! Veritatis omnis officiis quis corporis! Neque fuga adipisci sapiente vero deleniti beatae cupiditate explicabo amet doloremque, a nostrum enim sequi laborum quidem! Impedit animi itaque, nam recusandae asperiores non quod libero eligendi magni repellendus vel cupiditate nemo ipsum dignissimos quae mollitia, vero illum at aliquam hic facilis pariatur accusantium dolores quidem. Voluptas nemo nostrum maiores quas exercitationem consectetur laboriosam itaque facilis nam delectus adipisci quibusdam, nulla obcaecati quis minima officiis consequuntur corrupti? Ullam enim ratione laudantium corrupti eligendi a suscipit delectus, aut nobis tenetur! Ab praesentium eligendi officia inventore dolor, suscipit nemo fugit.
        </div>
    )
}
